### ISSUE TITLE
React v15.0.1 support

### ISSUE THREAD

**Issue by sarahkirby** [gilbox/react-track#10]
Hi there,

I'm wanting to use this awesome package but am running into some errors on install.
I think it might be because the peerDependencies require react ^0.14 & react-dom ^0.14 and I'm using the lastest versions - 15.0.1.

The errors are as follows:

npm install react-track --save
npm WARN package.json myresolutions@1.0.0 No description
npm WARN package.json myresolutions@1.0.0 No README data
npm WARN peerDependencies The peer dependency react@^0.14 included from react-track will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@^0.14 included from react-track will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "react-track" "--save"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-css-transition-group@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-mounter@1.2.0 wants react@0.14.x || 15.x.x
npm ERR! peerinvalid Peer react-track@0.3.1 wants react@^0.14

Any advice would be much appreciated.

Thanks,

Sarah.

**Comment by gilbox** [comment]
I think you should be able to test it by forcing the install

```
npm install react-track --force
```

After installing, if you determine that it works fine w/react@15 you could update the package.json and submit a PR to this repo. I'd be happy to merge it.

**Comment by gilbox** [comment]
should be ok now. please open another issue if you run into any problems
