### ISSUE TITLE
Setting Invalid HTML Properties on Div

### ISSUE THREAD

**Issue by hew** [gilbox/react-track#19]
Getting hit with this error:

![](https://s3.amazonaws.com/f.cl.ly/items/1d3y2d1Q0e233F422E2U/Image%202016-07-21%20at%204.38.59%20PM.png)

``` js
 render() {
          const {trackedRef = self.props.trackedRef || identity} = this.props;

          return <props.component
                    {...self.props}
                    {...this.props}
                    ref={r => trackedRef(self.nodeRef = r)} />
        }
```

Maybe something like 

``` js

 render() {

    const { 
        trackedRef = self.props.trackedRef || identity, 
        formulas, 
        ...style, 
        ...rest } = this.props

          return <props.component
                    { ...style }
                    ref={r => trackedRef(self.nodeRef = r)} />
        }
```

**Comment by gilbox** [comment]
hmm I think that the problem with your proposed solution is that you might want to pass through other props as well. it might be better to continue doing the pass-through but filter out props like `formulas` and `component`

**Comment by hew** [comment]
Yeah you are right. Maybe something like this?

``` js
 render() {

    const { 
        trackedRef = self.props.trackedRef || identity, 
        formulas,
        component, 
        ...rest } = this.props

          return <component
                    {...self.props} // ?
                    { ...rest }
                    ref={r => trackedRef(self.nodeRef = r)} />
        }
```

**Comment by gilbox** [comment]
👍

**Comment by daaain** [comment]
Sorry for the non-contribution, but any plans for landing this?

Or if it needs a PR / testing maybe I can help?

**Comment by gilbox** [comment]
@daaain yes, please help! It needs to be tested and PR'd.

**Comment by daaain** [comment]
@gilbox sorry that it took ages, but finally got around to have a look and the issue seems to be solved :)

**Comment by gilbox** [comment]
thanks for the contrib @daaain  ! what is your npm user name?

**Comment by gpbl** [comment]
thanks @daaain! any plan to publish the update on npm @gilbox 🙏 ?

**Comment by daaain** [comment]
Of course @gpbl, I totally missed that bit :|

Just pushed v0.4.1 now, please update!

**Comment by gpbl** [comment]
woot! awesome thanks @daaain !

**Comment by daaain** [comment]
Actually make it v0.4.2, I managed to publish before doing a build (and NPM doesn't allow republishing) :facepalm:

**Comment by gpbl** [comment]
@daaain np i know the pain :D Anway are you sure you have built the source before pushing? it seems it is still importing the src ... also, on this repo i still see 0.4.1. 

A way to skip this kind of issues on npm is to set `main` in `package.json` to (for example) `lib` and build into a `lib` dir. Then in my packages I .gitignore `lib`.

**Comment by daaain** [comment]
Oh, I forgot to push, but it's up now.

I did `npm run build-npm`, if it's still not quite working I think we need @gilbox to have a quick look, I'm very new to this project...

**Comment by gilbox** [comment]
@daaain thanks for taking the time to try to push this out! I think the problem is resolved now. [See here](https://github.com/gilbox/react-track/issues/21#issuecomment-255801068)
