### ISSUE TITLE
Provide a way to update TrackDocument component

### ISSUE THREAD

**Issue by lennerd** [gilbox/react-track#25]
Do you plan or already implemented a way to update a TrackDocument for example when the window/viewport size or the element size changed? Would it make sense to make `update` a public method of the component, which can be called via it's ref? Or maybe via the `componentDidUpdate` hook?

Thanks for your help in advance.

**Comment by gilbox** [comment]
I welcome PRs that improve the project. Is there a specific problem you're trying to solve?

**Comment by lennerd** [comment]
I already thought about making a PR for this. Just wonder as this project has a quite novel approach to pass in scroll offsets via a child callback function what you think a nice approach for updating the scroll state in certain situations would be.

Problem to solve is like I mentioned the situation where the bounding client rectangle of child elements changed without scrolling in the document. The current implementation of the TrackDocument component only listens to the mounting hook and window scroll events. But the rectangle can also change 1 via new content and therefore new height of the containing elements or 2 via resizing the window/viewport.

Listening to windows resize events would solve situation 1. Situation 2 IMHO can be solved via having a public `update` method on the TrackDocument component or via a `componentDidUpdate` hook.

An example for the `update` method accessible via a reference:
```js
class MyComponent extends React.Component {
  componentDidUpdate() {
    this.trackDocument.update();
  }

  render() {
    return (
      <TrackDocument ref={(ref) => this.trackDocument = ref}>
        {/* ... */}
      </TrackDocument>
    );
  }
}
```

What do you think?

**Comment by gilbox** [comment]
What you're proposing sounds perfectly reasonable to me. I just meant that unless you actually have a situation *right now* which does not work without this feature, it might be better to wait to implement this. You might find that in most situations calling update is not necessary because a change in the DOM is often a result of a re-render anyway.

**Comment by lennerd** [comment]
You're right. I thought I looked into any line, but did not saw that you retrieve the document client rectangle directly in the render function and therefore don't need an `componentDidUpdate` hook. Isn't this difficult when used with `react-dom`? Never the less I think an event handler for resizing the viewport is still needed, isn't it?

**Comment by gilbox** [comment]
> Isn't this difficult when used with react-dom? 

should be ok i think

> an event handler for resizing the viewport is still needed, isn't it?

I don't know, might depend on your use case. In [the demo](http://gilbox.github.io/react-track/examples/demo/demo.html) I don't have such a handler.

**Comment by lennerd** [comment]
>> Isn't this difficult when used with react-dom?
>
> should be ok i think

You're again right, as you check for `document`. Sorry for not looking closer into the code. 🙈 

I will take a second look into my use case. Maybe there is another problem why my code was not running correctly. Especially the fact, that the `componentDidUpdate` hook is not needed, makes me wonder the error maybe happened on my side. Thanks for your help.

**Comment by lennerd** [comment]
Okay, I found the problem. Your tracking components do everything correctly (and they do a great job btw!). I added a window resize handler forcing an update and therefore to restart formulas inside the `TrackingDocument`. Still not sure if this is the right way to go, but it looks quite "unhacky" to me.

Maybe you can give me a hint on this one.

I'm trying to build a `Sticky` component with a placeholder used inside the tracking formulas. This placeholder keeps track of the original position and space the `Sticky` component occupied originally. This is done via simple `css` rules.

The problem now happens when I try to recalculate the new height and width of the node inside the `Sticky` component. For example because the container size changed due to a resize.
I somehow need to reset the CSS rules to get the original position and space the `Sticky` component would occupy and then reset to the new width and height calculated.
Do you maybe already bumped into this problem? Or have a nice way in mind when to reset the `Sticky` component before it's position and space is calculated? Or is there a basic conceptual problem I created?

**Comment by lennerd** [comment]
Again was not thinking clearly. Found a better way. Sorry for spamming.
