### ISSUE TITLE
Using Track component and setting "component" property causes TypeError

### ISSUE THREAD

**Issue by timmygee** [gilbox/react-track#27]
For a tracked component such as:

```
                                <Track
                                  component={MyComponent}
                                  formulas={[docTopTop]}
                                >
                                  {
                                    (TrackedMyComponent, posTopTop) => {
                                      console.log(posTopTop)
                                      return <TrackedMyComponent { ...item } />;
                                    }
                                  }
                                </Track>
```

I get the following error in the console:

```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Track.componentWillReceiveProps (index.js:95)
    at ReactCompositeComponent.js:611
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:610)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at Object.updateChildren (ReactChildReconciler.js:109)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:208)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:312)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:299)
```

After a bit of digging, it appears that this [line](https://github.com/gilbox/react-track/blob/master/src/index.js#L39) evaluates to null. Passing a custom `trackedRef` property to the Track component did not help.

In the end I have worked around the issue by wrapping my component in a `TrackedDiv`.

I'm not sure what is the cause of the error at this stage but I expect you would get the issue setting the component property to a stateless functional component since that's what caused the error for me.

**Comment by gilbox** [comment]
Since SFCs don't support ref, wrapping them in a div is the only way to track them. This point should probably be added to the documentation. If you'd like to submit a PR updating the README explaining this it would be appreciated.

**Comment by timmygee** [comment]
Yeah that makes sense. Maybe one day I will see how support for stateless functional components can be supported as well but in the mean time I have submitted #28 to add a note to the readme.

**Comment by gilbox** [comment]
Great job, thanks for the PR!
