### ISSUE TITLE
react-track throws warning for React 15.5 PropTypes.

### ISSUE THREAD

**Issue by dlebedynskyi** [gilbox/react-track#29]
Any chance to migrate project  to React^15.5
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html ?

**Comment by gilbox** [comment]
Would love to. @dlebedynskyi you're suggesting making this change backwards-incompatible, correct?

**Comment by dlebedynskyi** [comment]
I think prop-types are compatible with any react version.  Should not effect versions below 15.5. Here is PR https://github.com/gilbox/react-track/pull/30. Would appreciate release soon)

**Comment by gilbox** [comment]
Thanks for the pr ( ◠‿◠ ) @dlebedynskyi 
I added you as a collaborator. Can you tell me your npm user name or create one if you don't have one already?

**Comment by dlebedynskyi** [comment]
@gilbox  npm user: dml. Thanks for merging this

**Comment by dlebedynskyi** [comment]
@gilbox would like to draft a new release with fix now?

**Comment by gilbox** [comment]
@dlebedynskyi I added you on npm. You can now publish a new release. Please read these instructions:

https://github.com/gilbox/react-track#publishing-to-npm

note that `npm run publish` is **not** the same as `npm publish`
