### ISSUE TITLE
React.findDOMNode error

### ISSUE THREAD

**Issue by hydrotik** [gilbox/react-track#4]
Not sure if this is react-track or react-imation yet, but getting this after upgrading to 0.2.2 with react-imation at 0.5.3

``` bash
[Error] Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```

**Comment by gilbox** [comment]
Thanks for reporting! Should be fixed now with version `0.3.0`.

**Comment by hydrotik** [comment]
Whoops, thought I had already upgraded. Sorry about that and thanks!

**Comment by gilbox** [comment]
Actually I fixed it after you reported ( ◠‿◠ )
