### ISSUE TITLE
put 0.3.1 version to npm registry

### ISSUE THREAD

**Issue by bexcite** [gilbox/react-track#8]
Hi Gil,

Thanks for the awesome library. I was trying to use it for our site but figured out that the latest version 0.3.1 is not yet in npm registry. Do you plan to release the `master` version to npm as version 0.3.1?

Because I desperately whant to use the latest version, which has a proper `removeEventListener` on componentWillUnmount for TackDocument.

Thanks for your job and looking forward to use the latest version directly from npm.

**Comment by gilbox** [comment]
Oops I must have forgotten to publish it. It's up there now.
